// Code generated by the klever-sc build system. DO NOT EDIT.
////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Total number of exported functions:   7

#![no_std]

klever_sc_wasm_adapter::allocator!(static64k);
klever_sc_wasm_adapter::panic_handler!();

klever_sc_wasm_adapter::endpoints! {
    issuer
    (
        init => init
        create_certificate => create_certificate
        check_certificate => check_certificate
        revoke_certificate => revoke_certificate
        change_expiration_date => change_expiration_date
        events_certificate => events_certificate
        proof_certificate => proof_certificate
    )
}
