[package]
name = "issuer"
version = "0.0.1"
authors = ["Kleverchain Team"]
edition = "2021"
publish = false

[lib]
path = "src/issuer.rs"

[dependencies.klever-sc]
version = "0.44.0"
features = ["alloc"]

[dev-dependencies.klever-sc-scenario]
version = "0.44.0"

[workspace]
members = [".", "meta"]
