[package]
name = "issuer-meta"
version = "0.0.1"
edition = "2021"
publish = false
[dependencies.issuer]
path = ".."

[dependencies.klever-sc-meta]
git = "https://github.com/klever-io/klever-vm-sdk-rs-internal"
rev = "0d90b14"
version = "*"
