[package]
name = "issuer-meta"
version = "0.0.1"
edition = "2021"
publish = false
[dependencies.issuer]
path = ".."

[dependencies.klever-sc-meta]
path = "/Users/beroni/klever/klever-vm-sdk-rs-internal/framework/meta"
version = "*"
